import streamlit as st
st.title("Demo Application")
st.write("This is a simple demo application using Streamlit.")
st.button("Click Me!")

st.title("Title")
st.header("Header")
st.subheader("Subheader")
st.text("This is some plain text.") 
st.write("Dynamic text")
st.button("Button")
st.text_input("Text Input", "Default Text")
st.number_input("Number Input")
st.selectbox("Select Box", [1, 2, 3])
st.slider("Slider", 0, 100)
st.error("This is an error message.")
st.warning("This is a warning message.")
st.info("This is an info message.")
st.success("This is a success message.")
